apiVersion: apps/v1
kind: Deployment
metadata:
  name: outyet
  labels:
    app: outyet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outyet
  template:
    metadata:
      labels:
        app: outyet
    spec:
      containers:
      - name: outyet
        image: spkane/outyet:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: outyet
  labels:
    name: outyet
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: outyet
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outyet-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: outyet
            port:
              number: 8080
