apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tools
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tools
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tools
  namespace: default
subjects:
- kind: ServiceAccount
  name: tools
  namespace: default
roleRef:
  kind: ClusterRole
  name: tools
  apiGroup: rbac.authorization.k8s.io
