apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools
  namespace: default
  labels:
    app: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
      - name: tools
        image: spkane/train-os:latest
        command: ["sleep"]
        args: ["infinity"]
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
