apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - https://github.com/kubernetes/ingress-nginx//deploy/static/provider/kind?ref=controller-v1.12.1
